name: GitHub Actions Pi-Gen upload Demo
run-name: ${{ github.actor }} is uploading github actions output
on: [push]
jobs:
  pi-gen-upload-image:
    runs-on: ubuntu-latest
    steps:
      - uses: usimd/pi-gen-action@v1
        id: build
        with:
          image-name: test

      - uses: actions/upload-artifact@v4
        with:
          name: pi-gen-image
          path: ${{ steps.build.outputs.image-path }}
